Repository netromdk/slacker, pull requests merged in 2018-02, with the labels that each got.

#69 Channels list command
  slacker/commands/__init__.py
  slacker/commands/channels/__init__.py
  slacker/commands/channels/channels_list_command.py
Labels: ready to merge

#79 Fixed key lookups in users.list
  slacker/commands/users/users_list_command.py
Labels: bug, ready to merge

#90 Double-quote conformity
  CONTRIBUTING.md
  slacker.py
  slacker/commands/api/api_test_command.py
  slacker/commands/argument_parser.py
  slacker/commands/auth/auth_test_command.py
  slacker/commands/channels/channels_list_command.py
  slacker/commands/chat/chat_memessage_command.py
  slacker/commands/chat/chat_postephemeral_command.py
  slacker/commands/chat/chat_postmessage_command.py
  slacker/commands/emoji/emoji_list_command.py
  slacker/commands/files/files_delete_command.py
  slacker/commands/files/files_list_command.py
  slacker/commands/general/config_command.py
  slacker/commands/general/log_command.py
  slacker/commands/general/workspace_command.py
  slacker/commands/registrar.py
  slacker/commands/users/users_list_command.py
  slacker/environment/config.py
  slacker/environment/constants.py
  slacker/logger.py
  slacker/main.py
  slacker/slack_api.py
  slacker/utility.py
Labels: needs rebase

#92 Test and ci
  .travis.yml
  README.md
  slacker/main.py
Labels: ready to merge

#103 Add slack integration
  .travis.yml
Labels: ready to merge

#96 Help alias
  slacker/commands/general/help_command.py
Labels: ready to merge
